### ISSUE TITLE
Consider using a command framework library

### ISSUE THREAD

**Issue by scarabcoder** [ifydev/Dimensify#7]
At the moment the command class ([DimensifyCommand.java](https://github.com/ifydev/Dimensify/blob/master/DimensifySpigot/src/main/java/me/ifydev/dimensifyspigot/commands/DimensifyCommand.java)) is rather cluttered, at worst it's difficult to find the entire command/argument structure. Using something like [ACF's popular annotation-based command framework](https://www.spigotmc.org/threads/acf-beta-annotation-command-framework.234266/) would make it both easier to read and maintain/modify.

**Comment by Innectic** [comment]
Using someone elses library will _not_ be considered. I already have something in the works within IfyCore that I will be using instead. As for the command being a mess, I haven't gone through the cleanup stage of the plugin yet :) Aaaaalllll of the logic will be moved out of there after that phase.
